app:
  protocol: tcp
  mode: client
  servers:
    - open-port: 9090
      client-port: 8080
  clients:
    - idle-num: 5
      remote-addr: 0.0.0.0:8080
      local-port: 7070
  log:
    path: ./logs
    size: 1
    age: 7
    backups: 1000