# server config
servers:
  - open-port: 9091
    tunnel-port: 8081

# client config
clients:
  - tunnel-addr: 0.0.0.0:8081
    local-port: 7071

# log file config
log:
  path: ./logs
  # maximum size of a single file
  size: 1
  # number of days to retain
  age: 30
  # maximum number of backup files
  backups: 1000