application:
  protocol: tcp
  mode: client
  server:
    listen-port: 9090
    client-port: 8080
  client:
    remote-addr: 0.0.0.0:8080
    local-port: 7070
    tunnel-num: 100
  log:
    path: ./logs
    size: 1
    age: 7
    backups: 1000